- xterm is replaced with /bin/rxvt on win32 only as there is   no xterm in Msys by default.
- The path to 'which' is hardcoded on win32 only, to prevent
  accidental use of a second (broken) version supplied with Mingw.

- Use psql's -o option to output data dumps to files in
  compare_pgbench_dumps. This avoids using the pager which is
  likely to be C:\windows\System32\more.com on Win32 and cannot
  handle more than 8MB of data at once.

Provided by Dave Page (dpage at vale-housing.co.uk)

diff --git a/src/ducttape/test_2_pgbench.in b/src/ducttape/test_2_pgbench.in
--- a/src/ducttape/test_2_pgbench.in
+++ b/src/ducttape/test_2_pgbench.in
@@ -1,7 +1,7 @@
 #!/bin/sh
-
+# $Id: test_2_pgbench.in,v 1.1 2005-07-04 23:45:21 darcyb Exp $
 # **********
-# test_5_pgbench
+# test_2_pgbench
 #
 # 	This test script creates a standalone pgbench database 
 #	as slony_test1 and then:
@@ -13,21 +13,27 @@
 #	- starts the second replication daemon
 #	- creates the pgbench tables (schema only)
 #	- subscribes the replication set from the primary node
-#
-#	This test differs from test_3 in that it adds the tables
-#	and custom triggers via ddl-script execution during
-#	replication.
+#	- creates a 3rd database node similar that replicates
+#	  cascaded from the second node.
+#	- waits until the pgbench is terminated and the user
+#	  stopped all 3 replication engines.
+#	- compares the 3 database.
 # **********
 
+TERMPROG=xterm
+WHICHPROG=which
+
+PATH=/usr/local/slony1/bin:$PATH
 export PATH
 TMPOUT=/tmp/output.$$
 DB1=slony_test1
 DB2=slony_test2
+DB3=slony_test3
 DEBUG_LEVEL=2
 
-PGBENCH_SCALE=1
-PGBENCH_CLIENTS=2
-PGBENCH_TRANS=`expr 30000 / $PGBENCH_CLIENTS`
+PGBENCH_SCALE=10
+PGBENCH_CLIENTS=5
+PGBENCH_TRANS=`expr 50000 / $PGBENCH_CLIENTS`
 
 trap '
 	echo ""
@@ -44,7 +50,11 @@ trap '
 		echo "**** killing node daemon 2"
 		kill -15 $slon2_pid
 	fi
-	exit 1
+	if [ ! -z $slon3_pid ] ; then
+		echo "**** killing node daemon 3"
+		kill -15 $slon3_pid
+	fi
+	exit -1
 ' 2 15
 
 ######################################################################
@@ -55,7 +65,7 @@ trap '
 #####
 # Make sure the install is up to date
 #####
-WGM=`which gmake | egrep '^/'`
+WGM=`$WHICHPROG gmake | egrep '^/'`
 if [ -z "$WGM" ] ; then
     MAKE=make
     CGNU=`make -v | grep GNU`
@@ -68,7 +78,7 @@ else
 fi
 echo -n "**** running 'make install' in src directory ... "
 if ! ${MAKE} -C .. install >$TMPOUT 2>&1 ; then
-    echo "failed"; cat $TMPOUT; rm $TMPOUT; exit 1
+    echo "failed"; cat $TMPOUT; rm $TMPOUT; exit -1
 fi
 echo "done"
 rm $TMPOUT
@@ -81,13 +91,15 @@ dropdb $DB1 || echo "**** ignored"
 sleep 1
 dropdb $DB2 || echo "**** ignored"
 sleep 1
+dropdb $DB3 || echo "**** ignored"
+sleep 1
 
 #####
 # Create the "Primary Node"
 #####
 echo "**** creating database for Node 1"
 
-createdb $DB1 || exit 1
+createdb $DB1 || exit -1
 pgbench -i -s $PGBENCH_SCALE $DB1
 pg_dump -s $DB1 >pgbench_schema.sql
 
@@ -116,17 +128,18 @@ echo "**** initializing $DB1 as Primary Node for Slony-I cluster T1"
 slonik <<_EOF_
 	cluster name = T1;
 	node 1 admin conninfo = 'dbname=$DB1';
-	node 2 admin conninfo = 'dbname=$DB2';
+	node 2 admin conninfo = 'dbname=$DB1';
+	node 3 admin conninfo = 'dbname=$DB1';
 	init cluster (id = 1, comment = 'Node 1');
 	echo 'Database $DB1 initialized as Node 1';
 _EOF_
 if [ $? -ne 0 ] ; then
 	kill $pgbench_pid;
-	exit 1
+	exit -1
 fi
 
 echo "**** starting the Slony-I node daemon for $DB1"
-xterm -title "Slon node 1" -e sh -c "slon -d$DEBUG_LEVEL T1 dbname=$DB1; echo -n 'Enter>'; read line" &
+$TERMPROG -title "Slon node 1" -e sh -c "slon -d$DEBUG_LEVEL T1 dbname=$DB1; echo -n 'Enter>'; read line" &
 slon1_pid=$!
 echo "slon[$slon1_pid] on dbname=$DB1"
 
@@ -135,12 +148,13 @@ slonik <<_EOF_
 	cluster name = T1;
 	node 1 admin conninfo = 'dbname=$DB1';
 	node 2 admin conninfo = 'dbname=$DB2';
+	node 3 admin conninfo = 'dbname=$DB3';
 
 	try {
 		table add key (node id = 1, fully qualified name = 'public.history');
 	}
 	on error {
-		exit 1;
+		exit -1;
 	}
 
 	try {
@@ -159,17 +173,16 @@ slonik <<_EOF_
 			key = serial, comment = 'Table accounts');
 	}
 	on error {
-		exit 1;
+		exit -1;
 	}
 _EOF_
-
 if [ $? -ne 0 ] ; then
 	echo "failed"
 	kill $pgbench_pid 2>/dev/null
 	kill $slon1_pid 2>/dev/null
 	cat $TMPOUT
 	rm $TMPOUT
-	exit 1
+	exit -1
 fi
 echo "**** set created"
 
@@ -179,7 +192,7 @@ echo "**** set created"
 if ! kill -0 $pgbench_pid 2>/dev/null ; then
 	echo "**** pgbench terminated ???"
 	kill $slon1_pid 2>/dev/null
-	exit 1
+	exit -1
 fi
 
 echo ""
@@ -196,7 +209,7 @@ echo "**** creating database for Node 2"
 if ! createdb $DB2 ; then
 	kill $pgbench_pid 2>/dev/null
 	kill $slon1_pid 2>/dev/null
-	exit 1
+	exit -1
 fi
 
 echo "**** initializing $DB2 as Node 2 of Slony-I cluster T1"
@@ -204,24 +217,25 @@ slonik <<_EOF_
 	cluster name = T1;
 	node 1 admin conninfo = 'dbname=$DB1';
 	node 2 admin conninfo = 'dbname=$DB2';
+	node 3 admin conninfo = 'dbname=$DB3';
+
 	try {
 		store node (id = 2, comment = 'Node 2');
 		store path (server = 1, client = 2, conninfo = 'dbname=$DB1');
 		store path (server = 2, client = 1, conninfo = 'dbname=$DB2');
-		store listen (origin = 1, receiver = 2);
-		store listen (origin = 2, receiver = 1);
 	}
 	on error { exit -1; }
 	echo 'Database $DB2 added as Node 2';
 _EOF_
+
 if [ $? -ne 0 ] ; then
 	kill $pgbench_pid 2>/dev/null
 	kill $slon1_pid 2>/dev/null
-	exit 1
+	exit -1
 fi
 
-echo "**** starting the Slony-I node daemon for $DB1"
-xterm -title "Slon node 2" -e sh -c "slon -d$DEBUG_LEVEL T1 dbname=$DB2; echo -n 'Enter>'; read line" &
+echo "**** starting the Slony-I node daemon for $DB2"
+$TERMPROG -title "Slon node 2" -e sh -c "slon -d$DEBUG_LEVEL T1 dbname=$DB2; echo -n 'Enter>'; read line" &
 slon2_pid=$!
 echo "slon[$slon2_pid] on dbname=$DB2"
 
@@ -231,7 +245,7 @@ echo "slon[$slon2_pid] on dbname=$DB2"
 if ! kill -0 $pgbench_pid 2>/dev/null ; then
 	echo "**** pgbench terminated ???"
 	kill $slon1_pid 2>/dev/null
-	exit 1
+	exit -1
 fi
 
 ######################################################################
@@ -246,14 +260,93 @@ slonik <<_EOF_
 	cluster name = T1;
 	node 1 admin conninfo = 'dbname=$DB1';
 	node 2 admin conninfo = 'dbname=$DB2';
+	node 3 admin conninfo = 'dbname=$DB3';
 
 	subscribe set ( id = 1, provider = 1, receiver = 2, forward = yes );
 _EOF_
+
 echo ""
 echo "**********************************************************************"
 echo "**** $DB2 should now be copying data and attempting to catch up."
 echo "**********************************************************************"
 echo ""
+
+######################################################################
+# Setup DB2 as a subscriber node and let it subscribe the replication
+# set of the running pgbench
+######################################################################
+# echo -n "**** Hit enter when node 2 is done with copy set"
+# read line
+sleep `expr 60 \* $PGBENCH_SCALE`
+echo "**** creating database for Node 3"
+if ! createdb $DB3 ; then
+	kill $pgbench_pid 2>/dev/null
+	kill $slon1_pid 2>/dev/null
+	kill $slon2_pid 2>/dev/null
+	exit -1
+fi
+
+echo "**** initializing $DB3 as Node 3 of Slony-I cluster T1"
+slonik <<_EOF_
+	cluster name = T1;
+	node 1 admin conninfo = 'dbname=$DB1';
+	node 2 admin conninfo = 'dbname=$DB2';
+	node 3 admin conninfo = 'dbname=$DB3';
+
+	store node (id = 3, comment = 'Node 3');
+
+	store path (server = 1, client = 3, conninfo = 'dbname=$DB1');
+	store path (server = 2, client = 3, conninfo = 'dbname=$DB2');
+	store path (server = 3, client = 1, conninfo = 'dbname=$DB3');
+	store path (server = 3, client = 2, conninfo = 'dbname=$DB3');
+
+	echo 'Database $DB2 added as Node 2';
+_EOF_
+
+if [ $? -ne 0 ] ; then
+	kill $pgbench_pid 2>/dev/null
+	kill $slon1_pid 2>/dev/null
+	kill $slon2_pid 2>/dev/null
+	exit -1
+fi
+
+echo "**** starting the Slony-I node daemon for $DB3"
+$TERMPROG -title "Slon node 3" -e sh -c "slon -d$DEBUG_LEVEL T1 dbname=$DB3; echo -n 'Enter>'; read line" &
+slon3_pid=$!
+echo "slon[$slon3_pid] on dbname=$DB3"
+
+#####
+# Check that pgbench is still running
+#####
+if ! kill -0 $pgbench_pid 2>/dev/null ; then
+	echo "**** pgbench terminated ???"
+	kill $slon1_pid 2>/dev/null
+	exit -1
+fi
+
+######################################################################
+# Create the pgbench tables and subscribe to set 1
+######################################################################
+echo "**** creating pgbench tables and subscribing Node 2 to set 1"
+(
+	cat pgbench_schema.sql
+) | psql -q $DB3
+slonik <<_EOF_
+	cluster name = T1;
+	node 1 admin conninfo = 'dbname=$DB1';
+	node 2 admin conninfo = 'dbname=$DB2';
+	node 3 admin conninfo = 'dbname=$DB3';
+
+	subscribe set ( id = 1, provider = 2, receiver = 3, forward = no );
+_EOF_
+
+echo ""
+echo "**********************************************************************"
+echo "**** $DB3 should now be copying data and attempting to catch up."
+echo "**********************************************************************"
+echo ""
+
+
 
 echo -n "**** waiting for pgbench to finish "
 while kill -0 $pgbench_pid 2>/dev/null ; do
@@ -264,45 +357,58 @@ echo "**** pgbench finished"
 echo "**** please terminate the replication engines when caught up."
 wait $slon1_pid
 wait $slon2_pid
+wait $slon3_pid
 
 kill $pgbench_pid 2>/dev/null
 kill $slon1_pid 2>/dev/null
 kill $slon2_pid 2>/dev/null
+kill $slon3_pid 2>/dev/null
 
 echo -n "**** comparing databases ... "
 psql $DB1 >dump.tmp.1.$$ <<_EOF_
-	select 'accounts:'::text, aid, bid, abalance, filler, lastuser
+	select 'accounts:'::text, aid, bid, abalance, filler
 			from accounts order by aid;
-	select 'accounts_audit:'::text, au_aid, au_seqno, au_delta, au_user, au_time
-			from accounts_audit order by au_aid, au_seqno;
 	select 'branches:'::text, bid, bbalance, filler
 			from branches order by bid;
 	select 'tellers:'::text, tid, bid, tbalance, filler
 			from tellers order by tid;
-	select 'tellers_sum:'::text, su_tid, su_sum
-			from tellers_sum order by su_tid;
 	select 'history:'::text, tid, bid, aid, delta, mtime, filler,
 			"_Slony-I_T1_rowID" from history order by "_Slony-I_T1_rowID";
 _EOF_
 psql $DB2 >dump.tmp.2.$$ <<_EOF_
-	select 'accounts:'::text, aid, bid, abalance, filler, lastuser
+	select 'accounts:'::text, aid, bid, abalance, filler
 			from accounts order by aid;
-	select 'accounts_audit:'::text, au_aid, au_seqno, au_delta, au_user, au_time
-			from accounts_audit order by au_aid, au_seqno;
 	select 'branches:'::text, bid, bbalance, filler
 			from branches order by bid;
 	select 'tellers:'::text, tid, bid, tbalance, filler
 			from tellers order by tid;
-	select 'tellers_sum:'::text, su_tid, su_sum
-			from tellers_sum order by su_tid;
+	select 'history:'::text, tid, bid, aid, delta, mtime, filler,
+			"_Slony-I_T1_rowID" from history order by "_Slony-I_T1_rowID";
+_EOF_
+psql $DB3 >dump.tmp.3.$$ <<_EOF_
+	select 'accounts:'::text, aid, bid, abalance, filler
+			from accounts order by aid;
+	select 'branches:'::text, bid, bbalance, filler
+			from branches order by bid;
+	select 'tellers:'::text, tid, bid, tbalance, filler
+			from tellers order by tid;
 	select 'history:'::text, tid, bid, aid, delta, mtime, filler,
 			"_Slony-I_T1_rowID" from history order by "_Slony-I_T1_rowID";
 _EOF_
 
-if diff dump.tmp.1.$$ dump.tmp.2.$$ >test_3.diff ; then
-	echo "success - databases are equal."
-	rm dump.tmp.?.$$
-	rm test_3.diff
+if diff dump.tmp.1.$$ dump.tmp.2.$$ >test_2.1-2.diff ; then
+	echo "success - databases 1 and 2 are equal."
+	rm dump.tmp.2.$$
+	rm test_2.1-2.diff
 else
-	echo "FAILED - see test_3.diff for database differences"
+	echo "FAILED - see test_2.1-2.diff for database differences"
+fi
+echo -n "**** comparing databases ... "
+if diff dump.tmp.1.$$ dump.tmp.3.$$ >test_2.1-3.diff ; then
+	echo "success - databases 1 and 3 are equal."
+	rm dump.tmp.3.$$
+	rm dump.tmp.1.$$
+	rm test_2.1-3.diff
+else
+	echo "FAILED - see test_2.1-3.diff for database differences"
 fi
diff --git a/src/ducttape/test_D_moveset.in b/src/ducttape/test_D_moveset.in
--- a/src/ducttape/test_D_moveset.in
+++ b/src/ducttape/test_D_moveset.in
@@ -1,7 +1,7 @@
-#!/bin/sh
-# $Id: test_3_pgbench,v 1.13 2005-05-04 20:43:16 cbbrowne Exp $
+#!/bin/sh    
+# $Id: test_D_moveset.in,v 1.1 2005-07-04 23:45:21 darcyb Exp $
 # **********
-# test_3_pgbench
+# test_D_moveset
 #
 # 	This test script creates a standalone pgbench database 
 #	as slony_test1 and then:
@@ -14,9 +14,15 @@
 #	- creates the pgbench tables (schema only)
 #	- subscribes the replication set from the primary node
 #
-#	This test differs from test_1 in that it adds tables,
-#	custom triggers and rewrite rules to the pgbench database.
+#       - when pgbench ends, it does a MOVE SET request
+#         and then runs pgbench for a while again against
+#         the new master node
+#
+#  The test is on MOVE SET
 # **********
+
+TERMPROG=xterm
+WHICHPROG=which
 
 export PATH
 TMPOUT=/tmp/output.$$
@@ -26,7 +32,7 @@ DEBUG_LEVEL=2
 
 PGBENCH_SCALE=1
 PGBENCH_CLIENTS=5
-PGBENCH_TRANS=`expr 30000 / $PGBENCH_CLIENTS`
+PGBENCH_TRANS=`expr 8000 / $PGBENCH_CLIENTS`
 
 trap '
 	echo ""
@@ -51,7 +57,10 @@ trap '
 # have the "application" (pgbench) running.
 ######################################################################
 
-WGM=`which gmake | egrep '^/'`
+#####
+# Make sure the install is up to date
+#####
+WGM=`$WHICHPROG gmake | egrep '^/'`
 if [ -z "$WGM" ] ; then
     MAKE=make
     CGNU=`make -v | grep GNU`
@@ -62,15 +71,23 @@ if [ -z "$WGM" ] ; then
 else
     MAKE=gmake
 fi
-#####
-# Make sure the install is up to date
-#####
 echo -n "**** running 'make install' in src directory ... "
 if ! ${MAKE} -C .. install >$TMPOUT 2>&1 ; then
     echo "failed"; cat $TMPOUT; rm $TMPOUT; exit 1
 fi
 echo "done"
 rm $TMPOUT
+
+PREAMBLE_FILE=/tmp/preamble.$$
+cat <<EOF > $PREAMBLE_FILE
+define origin 11;
+define sub1 22;
+cluster name = T1;
+node @origin admin conninfo='dbname=$DB1';
+node @sub1 admin conninfo='dbname=$DB2';
+EOF
+
+
 
 #####
 # Remove old databases, if they exist
@@ -84,60 +101,10 @@ sleep 1
 #####
 # Create the "Primary Node"
 #####
-echo "**** creating database for Node 1"
+echo "**** creating database for Node 11"
 
 createdb $DB1 || exit 1
 pgbench -i -s $PGBENCH_SCALE $DB1
-
-#
-# Add a little bit of twist to the pgbench database
-#
-psql $DB1 <<_EOF_
-	create table accounts_audit (
-		au_aid		integer,
-		au_seqno	serial,
-		au_delta	integer,
-		au_user		text,
-		au_time		timestamp,
-
-		primary key (au_aid, au_seqno),
-		foreign key (au_aid) references accounts
-	);
-
-	create function accounts_audit_trig () returns trigger as '
-	begin
-		--
-		-- Log all changes >= $800 in the special audit table
-		--
-		if abs(new.abalance - old.abalance) >= 800 then
-			insert into accounts_audit
-					(au_aid, au_delta, au_user, au_time)
-					values (new.aid, (new.abalance - old.abalance),
-							SESSION_USER, CURRENT_TIMESTAMP);
-		end if;
-
-		return new;
-	end;
-	' language plpgsql;
-	create trigger accounts_audit_trig after update on accounts
-		for each row execute procedure accounts_audit_trig();
-
-	create table tellers_sum (
-		su_tid		integer,
-		su_sum		integer,
-
-		primary key (su_tid),
-		foreign key (su_tid) references tellers
-	);
-	insert into tellers_sum (su_tid, su_sum)
-		select tid, 0 from tellers;
-
-	create rule tellers_sum as on update to tellers
-		do update tellers_sum 
-			set su_sum = su_sum + abs(new.tbalance - old.tbalance)
-			where su_tid = old.tid;
-_EOF_
-
 pg_dump -s $DB1 >pgbench_schema.sql
 
 #####
@@ -163,11 +130,9 @@ echo ""
 
 echo "**** initializing $DB1 as Primary Node for Slony-I cluster T1"
 slonik <<_EOF_
-	cluster name = T1;
-	node 1 admin conninfo = 'dbname=$DB1';
-	node 2 admin conninfo = 'dbname=$DB2';
-	init cluster (id = 1, comment = 'Node 1');
-	echo 'Database $DB1 initialized as Node 1';
+	include <$PREAMBLE_FILE>;
+	init cluster (id = @origin, comment = 'Node @origin');
+	echo 'Database $DB1 initialized as Node 11';
 _EOF_
 if [ $? -ne 0 ] ; then
 	kill $pgbench_pid;
@@ -175,45 +140,34 @@ if [ $? -ne 0 ] ; then
 fi
 
 echo "**** starting the Slony-I node daemon for $DB1"
-xterm -title "Slon node 1" -e sh -c "slon -d$DEBUG_LEVEL T1 dbname=$DB1; echo -n 'Enter>'; read line" &
+$TERMPROG -title "Slon node 11" -e sh -c "slon -d$DEBUG_LEVEL -s500 -g10 T1 dbname=$DB1; echo -n 'Enter>'; read line" &
 slon1_pid=$!
 echo "slon[$slon1_pid] on dbname=$DB1"
 
 echo "**** creating a replication set containing the 4 pgbench tables ... "
 slonik <<_EOF_
-	cluster name = T1;
-	node 1 admin conninfo = 'dbname=$DB1';
-	node 2 admin conninfo = 'dbname=$DB2';
-
+	include <$PREAMBLE_FILE>;
 	try {
-		table add key (node id = 1, fully qualified name = 'public.history');
+		table add key (node id = @origin, fully qualified name = 'public.history');
 	}
 	on error {
 		exit 1;
 	}
 
 	try {
-		create set (id = 1, origin = 1, comment = 'Set 1 - pgbench tables');
-		set add table (set id = 1, origin = 1,
+		create set (id = 1, origin = @origin, comment = 'Set 1 - pgbench tables');
+		set add table (set id = 1, origin = @origin,
 			id = 1, fully qualified name = 'public.accounts',
 			comment = 'Table accounts');
-		set add table (set id = 1, origin = 1,
+		set add table (set id = 1, origin = @origin,
 			id = 2, fully qualified name = 'public.branches',
 			comment = 'Table branches');
-		set add table (set id = 1, origin = 1,
+		set add table (set id = 1, origin = @origin,
 			id = 3, fully qualified name = 'public.tellers',
 			comment = 'Table tellers');
-		set add table (set id = 1, origin = 1,
+		set add table (set id = 1, origin = @origin,
 			id = 4, fully qualified name = 'public.history',
 			key = serial, comment = 'Table accounts');
-		set add table (set id = 1, origin = 1,
-			id = 5, fully qualified name = 'public.accounts_audit',
-			comment = 'Table accounts_audit');
-		set add table (set id = 1, origin = 1,
-			id = 6, fully qualified name = 'public.tellers_sum',
-			comment = 'Table tellers_sum');
-		set add sequence (set id = 1, origin = 1,
-			id = 7, fully qualified name = 'public.accounts_audit_au_seqno_seq');
 	}
 	on error {
 		exit 1;
@@ -249,27 +203,32 @@ echo ""
 # Setup DB2 as a subscriber node and let it subscribe the replication
 # set of the running pgbench
 ######################################################################
-echo "**** creating database for Node 2"
+echo "**** creating database for node 22"
 if ! createdb $DB2 ; then
 	kill $pgbench_pid 2>/dev/null
 	kill $slon1_pid 2>/dev/null
 	exit 1
 fi
 
-echo "**** initializing $DB2 as Node 2 of Slony-I cluster T1"
+echo "**** initializing $DB2 as node 22 of Slony-I cluster T1"
 slonik <<_EOF_
-	cluster name = T1;
-	node 1 admin conninfo = 'dbname=$DB1';
-	node 2 admin conninfo = 'dbname=$DB2';
+	include <$PREAMBLE_FILE>;
+	echo 'Creating node 22';
 	try {
-		store node (id = 2, comment = 'Node 2');
-		store path (server = 1, client = 2, conninfo = 'dbname=$DB1');
-		store path (server = 2, client = 1, conninfo = 'dbname=$DB2');
-		store listen (origin = 1, receiver = 2);
-		store listen (origin = 2, receiver = 1);
+		store node (id = @sub1, comment = 'node @sub1', event node = @origin);
+        } on error {
+	    echo 'could not establish node @sub1';
+	    exit -1;
 	}
-	on error { exit -1; }
-	echo 'Database $DB2 added as Node 2';
+	try {
+		store path (server = @origin, client = @sub1, conninfo = 'dbname=$DB1');
+		store path (server = @sub1, client = @origin, conninfo = 'dbname=$DB2');
+	}
+	on error { 
+	    echo 'could not establish paths between @origin and @sub1';
+	    exit -1; 
+	}
+	echo 'Database $DB2 added as node @sub1';
 _EOF_
 if [ $? -ne 0 ] ; then
 	kill $pgbench_pid 2>/dev/null
@@ -278,7 +237,7 @@ if [ $? -ne 0 ] ; then
 fi
 
 echo "**** starting the Slony-I node daemon for $DB1"
-xterm -title "Slon node 2" -e sh -c "slon -d$DEBUG_LEVEL T1 dbname=$DB2; echo -n 'Enter>'; read line" &
+$TERMPROG -title "Slon node 22" -e sh -c "slon -d$DEBUG_LEVEL -s10000 -o10000 -g10 T1 dbname=$DB2; echo -n 'Enter>'; read line" &
 slon2_pid=$!
 echo "slon[$slon2_pid] on dbname=$DB2"
 
@@ -295,16 +254,13 @@ fi
 # And now comes the moment where the big elephant starts to pee
 # and the attendants in the first row climb on their chairs ...
 ######################################################################
-echo "**** creating pgbench tables and subscribing Node 2 to set 1"
+echo "**** creating pgbench tables and subscribing node 22 to set 1"
 (
 	cat pgbench_schema.sql
 ) | psql -q $DB2
 slonik <<_EOF_
-	cluster name = T1;
-	node 1 admin conninfo = 'dbname=$DB1';
-	node 2 admin conninfo = 'dbname=$DB2';
-
-	subscribe set ( id = 1, provider = 1, receiver = 2, forward = yes );
+	include <$PREAMBLE_FILE>;
+	subscribe set ( id = 1, provider = @origin, receiver = @sub1, forward = yes );
 _EOF_
 
 echo ""
@@ -318,6 +274,38 @@ while kill -0 $pgbench_pid 2>/dev/null ; do
 	echo -n "."
 	sleep 10
 done
+echo "
+****************************************************************************
+**** Now, switch roles so that $DB2 becomes master, and $DB1 the slave. ****
+****************************************************************************
+"
+
+echo "**** switching $DB2 to be origin of Slony-I cluster T1"
+slonik <<_EOF_
+	include <$PREAMBLE_FILE>;
+	echo 'Lock set';
+	lock set (id = 1, origin = @origin);
+	move set (id = 1, old origin = @origin, new origin = @sub1);
+_EOF_
+if [ $? -ne 0 ] ; then
+	kill $pgbench_pid 2>/dev/null
+	kill $slon1_pid 2>/dev/null
+	exit 1
+fi
+
+echo <<EOF
+ Start up pgbench against $DB2
+EOF
+pgbench -n -s $PGBENCH_SCALE -c $PGBENCH_CLIENTS -t $PGBENCH_TRANS $DB2 &
+pgbench_pid=$!
+
+echo -n "**** waiting for pgbench to finish "
+while kill -0 $pgbench_pid 2>/dev/null ; do
+	echo -n "."
+	sleep 10
+done
+echo <<EOF
+
 echo "**** pgbench finished"
 echo "**** please terminate the replication engines when caught up."
 wait $slon1_pid
@@ -327,40 +315,7 @@ kill $pgbench_pid 2>/dev/null
 kill $slon1_pid 2>/dev/null
 kill $slon2_pid 2>/dev/null
 
-echo -n "**** comparing databases ... "
-psql $DB1 >dump.tmp.1.$$ <<_EOF_
-	select 'accounts:'::text, aid, bid, abalance, filler
-			from accounts order by aid;
-	select 'accounts_audit:'::text, au_aid, au_seqno, au_delta, au_user, au_time
-			from accounts_audit order by au_aid, au_seqno;
-	select 'branches:'::text, bid, bbalance, filler
-			from branches order by bid;
-	select 'tellers:'::text, tid, bid, tbalance, filler
-			from tellers order by tid;
-	select 'tellers_sum:'::text, su_tid, su_sum
-			from tellers_sum order by su_tid;
-	select 'history:'::text, tid, bid, aid, delta, mtime, filler,
-			"_Slony-I_T1_rowID" from history order by "_Slony-I_T1_rowID";
-_EOF_
-psql $DB2 >dump.tmp.2.$$ <<_EOF_
-	select 'accounts:'::text, aid, bid, abalance, filler
-			from accounts order by aid;
-	select 'accounts_audit:'::text, au_aid, au_seqno, au_delta, au_user, au_time
-			from accounts_audit order by au_aid, au_seqno;
-	select 'branches:'::text, bid, bbalance, filler
-			from branches order by bid;
-	select 'tellers:'::text, tid, bid, tbalance, filler
-			from tellers order by tid;
-	select 'tellers_sum:'::text, su_tid, su_sum
-			from tellers_sum order by su_tid;
-	select 'history:'::text, tid, bid, aid, delta, mtime, filler,
-			"_Slony-I_T1_rowID" from history order by "_Slony-I_T1_rowID";
-_EOF_
+echo "Terminated slons, pg_bench, comparing..."
 
-if diff dump.tmp.1.$$ dump.tmp.2.$$ >test_3.diff ; then
-	echo "success - databases are equal."
-	rm dump.tmp.?.$$
-	rm test_3.diff
-else
-	echo "FAILED - see test_3.diff for database differences"
-fi
+./compare_pgbench_dumps $DB1 $DB2
+rm $PREAMBLE_FILE
